/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 WholeIsland3.glb --transform 
Files: WholeIsland3.glb [42.25MB] > C:\Users\gregc\Documents\three_js\3JS_Testing\react-three-fibre\3d-model\public\model\WholeIsland3-transformed.glb [2.77MB] (93%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

const WholeIsland3 = (props) => {
  const { nodes, materials } = useGLTF("./model/WholeIsland3-transformed.glb");
  return (
    <group {...props} dispose={null} position={[50, -20, 0]}>
      <mesh
        geometry={nodes.mountains_003001.geometry}
        material={materials.Material}
        position={[-14.457, -0.14, 291.555]}
        rotation={[Math.PI / 2, 0, 2.178]}
        scale={4.118}
      />
      <mesh
        geometry={nodes.water_001001.geometry}
        material={materials.Transparent}
        position={[-23.038, 3.647, 5.688]}
        rotation={[Math.PI / 2, 0, 1.561]}
        scale={16.674}
      />
    </group>
  );
};

useGLTF.preload("./model/WholeIsland3-transformed.glb");

export default WholeIsland3;
