/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 artstand.glb --transform 
Files: artstand.glb [5.62MB] > C:\Users\gregc\Documents\Portfolio\website\client\public\model\artstand-transformed.glb [1.04MB] (81%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/artstand-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Art_stand.geometry} material={materials['art stand']} />
      <group position={[0, 0.995, -0.062]} rotation={[1.302, 0, 0]} scale={1.428}>
        <mesh geometry={nodes.Plane005.geometry} material={materials['Painting 4']} />
        <mesh geometry={nodes.Plane005_1.geometry} material={materials['Plywood cob pressed texture']} />
        <mesh geometry={nodes.Plane005_2.geometry} material={materials['White Board']} />
      </group>
    </group>
  )
}

useGLTF.preload('/artstand-transformed.glb')
