/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 campfire1.glb --transform 
Files: campfire1.glb [43.93MB] > C:\Users\gregc\Documents\Portfolio\website\client\public\model\campfire1-transformed.glb [5.26MB] (88%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/campfire1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fire_LOW.geometry} material={materials['fire.003']} position={[0.787, -0.01, 1.362]} />
      <mesh geometry={nodes.Bedding.geometry} material={materials.Bedding_Material} position={[-0.846, 0, -0.717]} />
      <mesh geometry={nodes.Props.geometry} material={materials.Props_Material} position={[-0.846, 0, -0.717]} />
      <mesh geometry={nodes.Structure.geometry} material={materials.Structure_Material} position={[-0.846, 0, -0.717]} />
      <mesh geometry={nodes.Tarp.geometry} material={materials.Tarp_Material} position={[-0.846, 0, -0.717]} />
    </group>
  )
}

useGLTF.preload('/campfire1-transformed.glb')
