/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 drone2.glb --transform 
Files: drone2.glb [29.77MB] > C:\Users\gregc\Documents\Portfolio\website\client\public\model\drone2-transformed.glb [7.26MB] (76%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/drone2-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['3D_printed_parts'].geometry} material={materials['3D PRINT']} position={[-0.001, -0.011, -0.098]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846} />
      <group position={[-0.001, 0.06, 0.131]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846}>
        <mesh geometry={nodes.Cube013.geometry} material={materials.camera} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['Architectural Glass']} />
        <mesh geometry={nodes.Cube013_2.geometry} material={materials['plastic not shiny']} />
        <mesh geometry={nodes.Cube013_3.geometry} material={materials.LAIDAI} />
      </group>
      <group position={[-0.001, 0.103, -0.034]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846}>
        <mesh geometry={nodes.Circle029.geometry} material={materials.Fabric} />
        <mesh geometry={nodes.Circle029_1.geometry} material={materials.Velcro} />
      </group>
      <mesh geometry={nodes.battery_body.geometry} material={materials['PLASTIKAS BATTERY']} position={[-0.001, 0.103, -0.034]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846} />
      <group position={[-0.001, 0.015, -0.085]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846}>
        <mesh geometry={nodes.Circle022.geometry} material={materials.capacitor} />
        <mesh geometry={nodes.Circle022_1.geometry} material={materials['srew capacitor']} />
      </group>
      <mesh geometry={nodes.Carbon_Fiber_Frame.geometry} material={materials['carbon plastic']} position={[-0.001, -0.011, 0.009]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846} />
      <group position={[-0.001, 0.002, 0.019]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846}>
        <mesh geometry={nodes.Plane017.geometry} material={materials['white plastic']} />
        <mesh geometry={nodes.Plane017_1.geometry} material={materials['CIRCUIT BOARD 1']} />
      </group>
      <mesh geometry={nodes.Drone_camera.geometry} material={materials['Material.002']} position={[-0.001, 0.018, 0.158]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846} />
      <mesh geometry={nodes.metal_clips.geometry} material={materials.metalas} position={[-0.015, 0.167, -0.105]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846} />
      <group position={[-0.206, 0.026, 0.192]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846}>
        <mesh geometry={nodes.Circle027.geometry} material={materials['metalas black ']} />
        <mesh geometry={nodes.Circle027_1.geometry} material={materials['metalas grovie ']} />
      </group>
      <mesh geometry={nodes.Motor_iner_parts.geometry} material={materials['coper vire']} position={[0.204, 0.031, -0.164]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846} />
      <mesh geometry={nodes.Screws_and_Nuts.geometry} material={materials.srew} position={[-0.035, -0.017, 0.063]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846} />
      <mesh geometry={nodes.spacers.geometry} material={materials['diamond pattern']} position={[-0.029, 0.029, 0.142]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846} />
      <mesh geometry={nodes.Wire_protection.geometry} material={materials['Brown wave basket']} position={[-0.001, -0.015, 0.009]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846} />
      <mesh geometry={nodes.ziptie.geometry} material={materials['plastikas grooves']} position={[-0.001, -0.011, -0.098]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.846} />
    </group>
  )
}

useGLTF.preload('/drone2-transformed.glb')
