/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 guitar3.glb --transform 
Files: guitar3.glb [21.99MB] > C:\Users\gregc\Documents\Portfolio\website\client\public\model\guitar3-transformed.glb [566.36KB] (97%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/guitar3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Circle003.geometry} material={materials.PaletteMaterial004} />
      <mesh geometry={nodes.Plane004.geometry} material={materials['Guard Label']} />
      <mesh geometry={nodes.Plane006.geometry} material={materials.PaletteMaterial005} />
      <mesh geometry={nodes.Plane007.geometry} material={materials.Wood_stand} />
      <mesh geometry={nodes.Vert.geometry} material={materials.PaletteMaterial006} />
      <mesh geometry={nodes.Circle030.geometry} material={materials.lightwood} />
      <mesh geometry={nodes.Circle030_1.geometry} material={materials.PaletteMaterial003} />
      <mesh geometry={nodes.Circle030_2.geometry} material={materials.darkwood} />
      <mesh geometry={nodes.Circle030_3.geometry} material={materials.PaletteMaterial002} />
      <mesh geometry={nodes.Plane031.geometry} material={materials['Plastic dark']} />
      <mesh geometry={nodes.Plane031_1.geometry} material={materials.BLACKWITHLOGO} />
    </group>
  )
}

useGLTF.preload('/guitar3-transformed.glb')
