/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 writers_desk.glb --transform 
Files: writers_desk.glb [50.24MB] > C:\Users\gregc\Documents\Portfolio\website\client\public\model\writers_desk-transformed.glb [5.72MB] (89%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/writers_desk-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.117, 0.889, 0.273]} rotation={[-1.572, 0.011, 0.185]}>
        <mesh geometry={nodes.Mesh009.geometry} material={materials['old book j']} />
        <mesh geometry={nodes.Mesh009_1.geometry} material={materials['old paper df']} />
      </group>
      <group position={[0.169, 0.88, -0.004]} rotation={[-2.951, 0.001, -Math.PI / 2]} scale={0.295}>
        <mesh geometry={nodes.BezierCurve001.geometry} material={materials.quiel} />
        <mesh geometry={nodes.BezierCurve001_1.geometry} material={materials.quill} />
      </group>
      <mesh geometry={nodes.pen_nib.geometry} material={materials['Material.001']} position={[0.169, 0.88, -0.004]} rotation={[-2.951, 0.001, -Math.PI / 2]} scale={0.295} />
      <mesh geometry={nodes.inkstand.geometry} material={materials.inkstand} position={[0.167, 0.894, 0]} scale={0.024} />
      <mesh geometry={nodes.clockk_5001.geometry} material={materials['材质.006']} />
      <mesh geometry={nodes.clockk_5001_1.geometry} material={materials['材质.001']} />
      <mesh geometry={nodes.clockk_5001_2.geometry} material={materials['材质.002']} />
      <mesh geometry={nodes.clockk_5001_3.geometry} material={materials['材质.003']} />
      <mesh geometry={nodes.clockk_5001_4.geometry} material={materials['材质.004']} />
      <mesh geometry={nodes.clockk_5001_5.geometry} material={materials['材质.005']} />
      <mesh geometry={nodes.clockk_5001_6.geometry} material={materials['材质.007']} />
      <mesh geometry={nodes.clockk_5001_7.geometry} material={materials['材质.008']} />
      <mesh geometry={nodes.clockk_5001_8.geometry} material={materials['材质.009']} />
      <mesh geometry={nodes.clockk_5001_9.geometry} material={materials['材质.010']} />
    </group>
  )
}

useGLTF.preload('/writers_desk-transformed.glb')
